<a href="https://colab.research.google.com/github/nausahadali/Python-Basic-to-Advance/blob/main/SimleRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
df.drop(['longitude','latitude'],axis=1,inplace=True)

In [ ]:
df

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...
16995,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df.iloc[:,-1]

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [ ]:
df.iloc[:,:-1]

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,15.0,5612.0,1283.0,1015.0,472.0,1.4936
1,19.0,7650.0,1901.0,1129.0,463.0,1.8200
2,17.0,720.0,174.0,333.0,117.0,1.6509
3,14.0,1501.0,337.0,515.0,226.0,3.1917
4,20.0,1454.0,326.0,624.0,262.0,1.9250
...,...,...,...,...,...,...
16995,52.0,2217.0,394.0,907.0,369.0,2.3571
16996,36.0,2349.0,528.0,1194.0,465.0,2.5179
16997,17.0,2677.0,531.0,1244.0,456.0,3.0313
16998,19.0,2672.0,552.0,1298.0,478.0,1.9797
16999,52.0,1820.0,300.0,806.0,270.0,3.0147

In [ ]:
X = df.iloc[:,:-1]

In [ ]:
y = df.iloc[:, -1]

In [ ]:
X

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,15.0,5612.0,1283.0,1015.0,472.0,1.4936
1,19.0,7650.0,1901.0,1129.0,463.0,1.8200
2,17.0,720.0,174.0,333.0,117.0,1.6509
3,14.0,1501.0,337.0,515.0,226.0,3.1917
4,20.0,1454.0,326.0,624.0,262.0,1.9250
...,...,...,...,...,...,...
16995,52.0,2217.0,394.0,907.0,369.0,2.3571
16996,36.0,2349.0,528.0,1194.0,465.0,2.5179
16997,17.0,2677.0,531.0,1244.0,456.0,3.0313
16998,19.0,2672.0,552.0,1298.0,478.0,1.9797
16999,52.0,1820.0,300.0,806.0,270.0,3.0147

In [ ]:
X[['total_rooms','total_bedrooms','population', 'households','median_income']] = scaler.fit_transform(X[['total_rooms','total_bedrooms','population', 'households','median_income']])

/tmp/ipykernel_1561/2746889572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[['total_rooms','total_bedrooms','population', 'households','median_income']] = scaler.fit_transform(X[['total_rooms','total_bedrooms','population', 'households','median_income']])

In [ ]:
X

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,15.0,1.361695,1.764204,-0.361184,-0.075998,-1.252543
1,19.0,2.296608,3.230441,-0.261865,-0.099404,-1.081483
2,17.0,-0.882462,-0.866956,-0.955354,-0.999252,-1.170105
3,14.0,-0.524186,-0.480230,-0.796793,-0.715774,-0.362600
4,20.0,-0.545747,-0.506328,-0.701830,-0.622148,-1.026454
...,...,...,...,...,...,...
16995,52.0,-0.195728,-0.344995,-0.455275,-0.343872,-0.799999
16996,36.0,-0.135174,-0.027073,-0.205236,-0.094203,-0.715727
16997,17.0,0.015292,-0.019955,-0.161675,-0.117609,-0.446663
16998,19.0,0.012999,0.029868,-0.114630,-0.060394,-0.997787
16999,52.0,-0.377848,-0.568015,-0.543268,-0.601343,-0.455363

In [ ]:
df.corr()

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
housing_median_age,1.000000,-0.360984,-0.320434,-0.295890,-0.302754,-0.115932,0.106758
total_rooms,-0.360984,1.000000,0.928403,0.860170,0.919018,0.195383,0.130991
total_bedrooms,-0.320434,0.928403,1.000000,0.881169,0.980920,-0.013495,0.045783
population,-0.295890,0.860170,0.881169,1.000000,0.909247,-0.000638,-0.027850
households,-0.302754,0.919018,0.980920,0.909247,1.000000,0.007644,0.061031
median_income,-0.115932,0.195383,-0.013495,-0.000638,0.007644,1.000000,0.691871
median_house_value,0.106758,0.130991,0.045783,-0.027850,0.061031,0.691871,1.000000

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
test = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
xy = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
test = test.iloc[:,:-1]

In [ ]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375
...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608

In [ ]:
test[['total_rooms','total_bedrooms','population', 'households','median_income']] = scaler.fit_transform(test[['total_rooms','total_bedrooms','population', 'households','median_income']])

In [ ]:
test.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-122.05,37.37,27.0,0.596418,0.315337,0.130246,0.317734,1.510745
1,-118.30,34.26,43.0,-0.505550,-0.529255,-0.576296,-0.582743,-0.112324
2,-117.81,33.78,27.0,0.459078,-0.055225,0.078808,0.013926,1.071149
3,-118.36,33.82,28.0,-1.175083,-1.239098,-1.313894,-1.310788,1.255865
4,-119.67,36.33,19.0,-0.630362,-0.688068,-0.536504,-0.692223,-0.469081

In [ ]:
test.drop(['longitude','latitude'], axis=1,inplace=True)

In [ ]:
test.head()

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,27.0,0.596418,0.315337,0.130246,0.317734,1.510745
1,43.0,-0.505550,-0.529255,-0.576296,-0.582743,-0.112324
2,27.0,0.459078,-0.055225,0.078808,0.013926,1.071149
3,28.0,-1.175083,-1.239098,-1.313894,-1.310788,1.255865
4,19.0,-0.630362,-0.688068,-0.536504,-0.692223,-0.469081

In [ ]:
test_pred = model.predict(test)

In [ ]:
actual_pred = xy.iloc[:,-1]

In [ ]:
actual_pred

0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64

In [ ]:
model.score(test, xy.iloc[:,-1])

0.5445284627732035

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(actual_pred, test_pred)

In [ ]:
mse

5826300053.207401